package io.zonk.jbomberman.game;

public enum ActionType {
	LOBBY_COMMUNICATION,
	PLAYER_INPUT,
	MOVEMENT,
	SEND,
	CREATE_SOLIDBLOCK,
	CREATE_DESTROYABLEBLOCK,
	CREATE_BOMBERMAN,
	CREATE_BOMB,
	CREATE_EXPLOSION,
	CREATE_POWERUP,
	DESTROY,
	START_GAME
}
